#pragma once

namespace tpp
{
	enum Pattern { CHESSBOARD, CIRCLES_GRID, ASYMMETRIC_CIRCLES_GRID };

	enum Mode_To_Revtreive_Files { DIRECTORY, JSFILES };

	enum Type_Of_Result { ONLY_CALIBRATION, CALIBRATION_AND_3D_RECONSTRUCTION, _3D_RECONSTRUCTION };

	enum Type_Of_Calibration { MONO, STEREO, MONO_STEREO };

	enum USE_RECTIFIED_3D_POINTS_GRID { YES, NO };

	enum IS_STEREO_CALIBRATED { ALREADY_CALIBRATED, NOT_CALIBRATED };

	enum OBJECT_POINT_FEATURE { MAX_INTENSITY, LOWER_POINT, CLOUD_OF_POINT, UPPER_POINT, GRAVITY_CENTER };

	enum FIT_PLANE_CLOUD_POINT { FIT, NOT_FIT };
}